#!/usr/bin/env python3
"""Reproduce all paper tables."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from bdvr1.config import OUTPUT_TABLES, SPARC_PATHS, XGASS_PATHS, SPARC_CURRENT_SCORE_COL, SPARC_CURRENT_QUARTILE_COL
from bdvr1.io import read_table, write_table


def main():
    # Table 1: SPARC sample selection
    sparc_proxy_path = SPARC_PATHS["proxy_table"]
    if sparc_proxy_path.exists():
        df = read_table(sparc_proxy_path)
        selection = df[["galaxy_name", "Q", "T", "Vflat", "Inc", "Rdisk", "RHI",
                        "Mbar_msun", "logMbar",
                        SPARC_CURRENT_SCORE_COL, SPARC_CURRENT_QUARTILE_COL,
                        "btfr_residual_dex", "btfr_abs_residual"]].copy()
        write_table(selection, OUTPUT_TABLES / "table1_sparc_sample_selection.csv")
        print(f"Table 1: SPARC sample selection ({len(selection)} galaxies)")
    else:
        print("SPARC proxy table not found, skipping Table 1")

    # Tables 2 and others are generated by scripts 04 and 05
    # Copy from data/derived and outputs/tables
    for src_name, dst_name in [
        ("proxy_ablation_results.csv", "table2_xgass_proxy_ablation.csv"),
    ]:
        src = ROOT / "data/derived" / src_name
        dst = ROOT / "outputs/tables" / dst_name
        if src.exists():
            df = read_table(src)
            write_table(df, dst)
            print(f"Table: {dst_name} ({len(df)} rows)")

    print("All tables generated in outputs/tables/")


if __name__ == "__main__":
    main()
